### ISSUE TITLE
Doesn't work on some networks

### ISSUE THREAD

**Issue by circa-one** [ParabolicMinds/ParaTracker#37]
I haven't quite pinned down the criteria for which this issue arises from. But basically for some people they get a Could not connect to server error with the following error in the iframe:

```
<!--﻿<!-- ParaTracker 1.4.1 ﻿<br />
<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/srv/ParaTracker/ParaFunc.php</b> on line <b>1918</b><br />
<!---->
```

But for a lot of people, the tracker works fine. We haven't pinned down that its browser specific. On my home network it works on all browsers. On someone else's network it doesn't work on any. It would be strange if it was ISP specific.

**Comment by nab622** [comment]
The issue has been fixed. The PHP error message was unrelated and due to my incorrect use of count() instead of strlen(), but I changed the affected areas in the code so that neither usage was required.

The "Could not connect" error was a separate error, stemming from Javascript terminating partway through the update process. This was because Javascript was being used to read CSS classes, but a recent Chrome update blocked Javascript from reading CSS. Firefox also prevented Javascript from reading CSS.

Both issues are fixed. Unfortunately, the scroll bar on the player list had to be removed to fix this issue.
